export enum ItemSort {
	RECENTLY_UPDATED = 'RECENTLY_UPDATED',
	RECENTLY_ADDED = 'RECENTLY_ADDED',
	RELEASE_DATE = 'RELEASE_DATE',
	TRENDING = 'TRENDING',
	NAME = 'NAME',
	SCORE = 'SCORE',
	IMDB_VOTES = 'IMDB_VOTES',
	MOST_WATCHED = 'MOST_WATCHED',
	MOST_FAVOURITED = 'MOST_FAVOURITED',
}
